---
- name: Update all packages on RHEL
  hosts: all
  become: true
  vars:
    report_path: "/tmp/rhel_patch_report.txt"
  
  tasks:
  - name: Update all installed packages using DNF module
    ansible.builtin.dnf:
      name: '*'
      state: latest
      # exclude: '{{ excluded_pks }}'
      update_cache: true
      update_only: true
    register: dnf_update_status
    
  - name: Create report
    ansible.builtin.template:
      src: ../../files/patch_report.j2
      dest: "{{ report_path }}"
      mode: "0644"
    check_mode: false
  
  - name: Check to see if we need a reboot
    ansible.builtin.command: needs-restarting -r
    register: result
    ignore_errors: true

  - name: Store DNF results as facts
    ansible.builtin.set_fact: 
      last_update: "{{ dnf_update_status }}"

  - name: Reboot when required
    ansible.builtin.reboot:
      msg: "Reboot initiated by Ansible"
    when: result.rc == 1
