---
- name: Setup Controller for Workshop
  hosts: all
  gather_facts: false

  tasks:
    - name: Create AWS EC2 Credential
      ansible.controller.credential:
        name: "AWS EC2 Credential"
        credential_type: "Amazon Web Services"
        organization: Default
        state: present
        inputs:
          username: "{{ aws_username }}"
          password: "{{ aws_password }}"
          
    - name: Create SSH Key Credential for EC2
      ansible.controller.credential:
        name: "SSH Key for EC2 Credential"
        credential_type: "Machine"
        organization: Default
        state: present
        inputs:
          ssh_key_data: "{{ lookup('file', '../files/workshop_key') }}"
          username: "{{ ssh_username }}"
          become_method: sudo
          
    - name: Create AWS Inventory
      ansible.controller.inventory_source:
        name: 'ec2'
        organization: 'Default'
        source: 'ec2'
        inventory: 'Workshop Inventory'
        credential: 'AWS EC2 Credential'
        overwrite: true
        source_vars:
          hostnames:
            - tag:Name
          compose:
            ansible_host: public_ip_address
            ansible_user: 'ec2-user'
          groups:
            cloud_aws: true
            os_linux: tags.blueprint.startswith('rhel')
          keyed_groups:
            - key: platform
              prefix: os
            - key: tags.blueprint
              prefix: blueprint
            - key: tags.owner
              prefix: owner
