---
- name: DNF - check last Return-Code
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: DNF - gather last transaction stdout
      shell: `dnf history info last -q|sed 's/[[:space:]]//g'`
      register: dnf_history_output
      changed_when: false # indicate no system modifications.
      check_mode: false # disable checking for changes.
      when: ansible_pkg_mgr == 'dnf'

    - name: DEBUG - command outout
      ansible.builtin.debug:
        var: dnf_history_output.stdout_lines

    - name: Convert output to dictionary
      set_fact:
        output: "{{ dnf_history_output.stdout_lines[6] | split(':') }}"
       
    - name: DEBUG - command outout
      ansible.builtin.debug:
        var: output        
