---
- hosts: localhost
  become: no
  gather_facts: no
 
  tasks:
  - name: Print all available facts
    ansible.builtin.debug:
      msg: '{{ ansible_eda.event }}'

  - name: Print var
    ansible.builtin.debug:
      msg: '{{ foo }}'
      
