---
- name: Update all packages on RHEL
  hosts: all
  become: true
  gather_facts: true
   
  tasks:   
  - name: Update all installed packages using DNF module
    ansible.builtin.dnf:
      name: '*'
      state: latest
      update_cache: yes
      update_only: yes
    register: dnf_update_status
    
  - name: Setting host facts using complex arguments
    ansible.builtin.set_fact:
      one_fact: something
