---
- hosts: all

  tasks:  
  - name: Register with activationkey and consume subscriptions matching Red Hat Enterprise Server
    redhat.rhel_system_roles.redhat_subscription:
      state: present
      activationkey: "{{ activationkey }}"
      org_id: "{{ org_id }}"
      
  - name: Update all installed packages using DNF module
    ansible.builtin.dnf:
      name: '*'
      state: latest
      update_cache: yes
      update_only: yes
    register: dnf_update_status
  
  - name: Reboot when packages were updated
    ansible.builtin.reboot:
      msg: "Reboot initiated by Ansible"
    when: dnf_update_status.changed
