---
- name: Create ticket with notes
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Create a ServiceNow change request
    servicenow.itsm.incident:
      instance: 
        host: "{{ snow_host }}"
        username: "{{ snow_user }}"
        password: "{{ snow_password }}"
      state: new
      caller: "{{ snow_caller }}"
      priority: moderate
      impact: medium
      urgency: medium
      short_description: "{{ snow_desc_short }}"
      description: "{{ snow_desc_long }}"
    register: new_ticket
    
  - name: Print details from previous task
    ansible.builtin.debug:
      var: new_ticket
