---
- name: Get ESXI Hosts and create Inventory
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: Get a list of all ESXi hosts
    vmware.vmware_rest.vcenter_host_info:
    register: my_hosts

  - name: Remove Existing ESXI inventory
    ansible.controller.tower_inventory:
      name: "{{ inventory_name }}"
      description: "{{ inventory_desc }}"
      organization: "{{ inventory_org}}"
      state: absent

  - name: Add ESXI inventory tower inventory
    ansible.controller.tower_inventory:
      name: "{{ inventory_name }}"
      description: "{{ inventory_desc }}"
      organization: "{{ inventory_org }}"
      state: present


  - name: Add ESXi hosts to tower inventory
    ansible.controller.tower_host:
      name: "{{ item.name }}"
      description: "ESXi host imported from VCenter"
      inventory: "{{ inventory_name }}"
      state: present
      variables:
        connection_state: "{{ item.connection_state }}"
        host: "{{ item.host }}"
        power_state: "{{ item.power_state }}"
    loop: "{{ my_hosts.value }}"
