---
- hosts: webserver
  become: yes
  
  tasks:
  - name: Install required packages
    package:
      name: "{{ webserver_packages }}"
      state: latest
      
  - name: Enable service to start on boot up
    service:
      name: httpd
      enabled: yes
      state: started
      
  - name: Enable service to start on boot up
    service:
      name: firewalld
      enabled: yes
      state: started     
      
  - name: Create firewall rule for apache service
    firewalld:
      service: http
      zone: public
      permanent: yes
      immediate: yes
      state: enabled
      
  - name: Copy a custom index.html file
    get_url:
      url: https://raw.githubusercontent.com/caetanomedeiros/ansible-demos/main/files/index.html
      dest: /var/www/html/index.html
      force: true
      
  handlers:
  - name: Restart apache service
    service:
      name: httpd
      state: reload
