- name: Run Updates on Windows
  hosts: windows
  gather_facts: no
  
  tasks:
  - name: Windows update
    ansible.windows.win_updates:
      category_names:
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
      reboot: yes
      reboot_timeout: 600
